"""create profiles table

Revision ID: 32dd96eaa435
Revises: 
Create Date: 2025-11-05 23:21:18.705598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dd96eaa435'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('user_id', sa.String(), nullable=False, comment="Stack Auth user ID from JWT 'sub' claim"),
    sa.Column('free_swipes_remaining', sa.Integer(), nullable=False, comment='Free job application swipes (10 granted on registration)'),
    sa.Column('paid_credits', sa.Integer(), nullable=False, comment='Paid credits purchased by user'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Profile creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last profile update timestamp'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
